//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplicationFrontend.CartWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CartWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CartWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback addToCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeFromCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserCartDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTotalPriceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CartWebService() {
            this.Url = global::WebApplicationFrontend.Properties.Settings.Default.WebApplicationFrontend_CartWebService_CartWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event addToCartCompletedEventHandler addToCartCompleted;
        
        /// <remarks/>
        public event removeFromCartCompletedEventHandler removeFromCartCompleted;
        
        /// <remarks/>
        public event getUserCartDetailsCompletedEventHandler getUserCartDetailsCompleted;
        
        /// <remarks/>
        public event getTotalPriceCompletedEventHandler getTotalPriceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addToCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string addToCart(int userId, int productId) {
            object[] results = this.Invoke("addToCart", new object[] {
                        userId,
                        productId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addToCartAsync(int userId, int productId) {
            this.addToCartAsync(userId, productId, null);
        }
        
        /// <remarks/>
        public void addToCartAsync(int userId, int productId, object userState) {
            if ((this.addToCartOperationCompleted == null)) {
                this.addToCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddToCartOperationCompleted);
            }
            this.InvokeAsync("addToCart", new object[] {
                        userId,
                        productId}, this.addToCartOperationCompleted, userState);
        }
        
        private void OnaddToCartOperationCompleted(object arg) {
            if ((this.addToCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addToCartCompleted(this, new addToCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/removeFromCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string removeFromCart(int cartId) {
            object[] results = this.Invoke("removeFromCart", new object[] {
                        cartId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void removeFromCartAsync(int cartId) {
            this.removeFromCartAsync(cartId, null);
        }
        
        /// <remarks/>
        public void removeFromCartAsync(int cartId, object userState) {
            if ((this.removeFromCartOperationCompleted == null)) {
                this.removeFromCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveFromCartOperationCompleted);
            }
            this.InvokeAsync("removeFromCart", new object[] {
                        cartId}, this.removeFromCartOperationCompleted, userState);
        }
        
        private void OnremoveFromCartOperationCompleted(object arg) {
            if ((this.removeFromCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeFromCartCompleted(this, new removeFromCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserCartDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getUserCartDetails(int userId) {
            object[] results = this.Invoke("getUserCartDetails", new object[] {
                        userId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUserCartDetailsAsync(int userId) {
            this.getUserCartDetailsAsync(userId, null);
        }
        
        /// <remarks/>
        public void getUserCartDetailsAsync(int userId, object userState) {
            if ((this.getUserCartDetailsOperationCompleted == null)) {
                this.getUserCartDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserCartDetailsOperationCompleted);
            }
            this.InvokeAsync("getUserCartDetails", new object[] {
                        userId}, this.getUserCartDetailsOperationCompleted, userState);
        }
        
        private void OngetUserCartDetailsOperationCompleted(object arg) {
            if ((this.getUserCartDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserCartDetailsCompleted(this, new getUserCartDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTotalPrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTotalPrice(int userId) {
            object[] results = this.Invoke("getTotalPrice", new object[] {
                        userId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTotalPriceAsync(int userId) {
            this.getTotalPriceAsync(userId, null);
        }
        
        /// <remarks/>
        public void getTotalPriceAsync(int userId, object userState) {
            if ((this.getTotalPriceOperationCompleted == null)) {
                this.getTotalPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTotalPriceOperationCompleted);
            }
            this.InvokeAsync("getTotalPrice", new object[] {
                        userId}, this.getTotalPriceOperationCompleted, userState);
        }
        
        private void OngetTotalPriceOperationCompleted(object arg) {
            if ((this.getTotalPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTotalPriceCompleted(this, new getTotalPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void addToCartCompletedEventHandler(object sender, addToCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addToCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addToCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void removeFromCartCompletedEventHandler(object sender, removeFromCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeFromCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeFromCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getUserCartDetailsCompletedEventHandler(object sender, getUserCartDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserCartDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserCartDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void getTotalPriceCompletedEventHandler(object sender, getTotalPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTotalPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTotalPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591